{
 "title": "JMeter",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus exporter",
 "tags": [ "jmeter" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(jsr223_count_total[$interval]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(jsr223_rt_as_summary_sum{code=\"200\"}[$interval])/(rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg(rate(jsr223_failure_total[$interval]))/avg(rate(jsr223_count_total[$interval])))"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Virtual Users vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum(rate(jsr223_success_total[$interval]))",
     "legendFormat": "Request OK per second"
    },
    {
     "expr": "sum(rate(jsr223_failure_total[$interval]))   ",
     "legendFormat": "Request KO per second"
    }
   ]
  },
  {
   "title": "Total Requests vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jsr223_success_total[$interval]))/sum(rate(jsr223_count_total[$interval])))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(jsr223_failure_total[$interval]))/sum(rate(jsr223_count_total[$interval])))",
     "legendFormat": "KO"
    },
    {
     "expr": "sum(rate(jsr223_count_total[$interval]))",
     "legendFormat": "Total Requests per second"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(jsr223_rt_as_summary_sum{code=\"200\"}[$interval])/(rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(jsr223_rt_as_summary_sum{code=\"200\"}[$interval])/(rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(rate(jsr223_success_total[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(jsr223_failure_total[$interval]))   ",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "OK",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(jsr223_success_total) by (label) "
    }
   ]
  },
  {
   "title": "KO",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(jsr223_failure_total) by (label) "
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Avg. response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": " avg (rate(jsr223_rt_as_summary_sum{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval]) / (rate(jsr223_rt_as_summary_count{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval])>0)) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "Pct response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jsr223_rt_as_summary{code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jsr223_success_total[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(jsr223_failure_total[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jsr223_count_total[$interval])) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(jsr223_count_total_code[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Test farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "GC % time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"monitoring/connect-perf-tests.*\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}} "
    }
   ]
  },
  {
   "title": "JVM heap  - free memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_committed {job=~\"monitoring/connect-perf-tests.*\"}) - (jvm_memory_pool_bytes_used{job=~\"monitoring/connect-perf-tests.*\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM heap -  used memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{job=~\"monitoring/connect-perf-tests.*\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_max {job=~\"monitoring/connect-perf-tests.*\"}) - (jvm_memory_bytes_used{job=~\"monitoring/connect-perf-tests.*\"})",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  }
 ]
}