version: "3.9"
services:
  vault:
    container_name: VAULT
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vault
    cap_add:
      - IPC_LOCK
