version: "2.1"
services:

  prometheus:
    container_name: PROMETHEUS
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
 #grafana:
 #  container_name: GRAFANA
 #  image: grafana/grafana:latest
 #  networks:
 #    - jmeter-network
 #  ports:
 #    - "3000:3000"
 #  environment:
 #    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
 #    - GF_AUTH_ANONYMOUS_ENABLED=true
 #    - GF_AUTH_BASIC_ENABLED=false
 #  volumes:
 #     - ./grafana:/etc/grafana/provisioning/
  jmeter-master:
    container_name: MASTER
    build:
      dockerfile: Dockerfile-master
      context: .
    environment:
      - SLAVE_HOSTS=jmeter-slave-0,jmeter-slave-1
     # - SLAVE_HOSTS=jmeter-slave-0
    depends_on:
      - jmeter-slave-0
      - jmeter-slave-1
     # - jmeter-slave-2
    volumes:
      - ./scenario.jmx:/config/mount/test-plan/scenario.jmx
  #    - ./jmeter/bin/test.properties:/config/mount/test-properties/test.properties
    networks:
      - jmeter-network
  jmeter-slave-0:
    container_name: SLAVE-0
    build:
      dockerfile: Dockerfile-slave
      context: .
    environment:
      - HOSTNAME=1
    ports:
      - "9270:9270"
   #volumes:
      #- ./data/keycloak-users-1.csv:/config/mount/test-data/testdata.csv
    networks:
      - jmeter-network
#
  jmeter-slave-1:
    container_name: SLAVE-1
    build:
      dockerfile: Dockerfile-slave
      context: .
    ports:
      - "9271:9270"
    #volumes:
      #- ./data/keycloak-users-1.csv:/config/mount/test-data/testdata.csv
    networks:
      - jmeter-network

networks:
  jmeter-network:
